name: Issue Event Example

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Details
        id: print_details
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Opened By: ${{ github.event.issue.user.login }}"
          echo "Labels: ${{ join(github.event.issue.labels.*.name, ', ') }}"
