name: Handle issues
on: issues
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
<<<<<<< HEAD
        run: echo "${{ toJSON(github.event) }}"
=======
        run: echo "${{ toJSON(github.event) }}"
>>>>>>> origin/main
